export const POSTS_LIMIT = 5;
export const SPORTS = [
  "Acrobatics",
  "Aerobic Gymnastics",
  "Archery",
  "Arnis",
  "Artistic Gymnastics",
  "Artistic Swimming",
  "Badminton",
  "Baseball",
  "Basketball",
  "Baton Twirling",
  "BMX",
  "Billiards",
  "Bobsleigh",
  "Bodybuilding",
  "Bowling",
  "Boxing",
  "Canoeing",
  "Car Racing",
  "Cheerleading",
  "Chess",
  "Cricket",
  "Croquet",
  "Curling",
  "Dance Sport",
  "Darts",
  "Diving",
  "Dodgeball",
  "Fencing",
  "Figure Skating",
  "Football",
  "Frisbee",
  "Golf",
  "Handball",
  "Hang Gliding",
  "Hockey",
  "Horseback Riding",
  "Horse Racing",
  "Ice Hockey",
  "Ice Skating",
  "Jet Ski Racing",
  "Judo",
  "Karate",
  "Kayaking",
  "Kendo",
  "Kick Boxing",
  "Kite Surfing",
  "Lacrosse",
  "Luge",
  "Mixed Martial Arts",
  "Motocross",
  "Muay Thai",
  "Paintball",
  "Parachuting",
  "Paragliding",
  "Parkour",
  "Polo",
  "Pool/Billiards",
  "Powerlifting",
  "Rafting",
  "Rhythmic Gymnastics",
  "Rock Climbing",
  "Rowing",
  "Running",
  "Rugby",
  "Sailing",
  "Sandboarding",
  "Scuba Diving",
  "Shooting",
  "Skateboarding",
  "Skeleton",
  "Skiing",
  "Snowboarding",
  "Softball",
  "Speed Skating",
  "Sport Climbing",
  "Squash",
  "Sumo Wrestling",
  "Surfing",
  "Swimming",
  "Synchronized Skating",
  "Synchronized Swimming",
  "Table Tennis",
  "Taekwondo",
  "Tennis",
  "Track and Field",
  "Trampolining",
  "Triathlon",
  "Tug of War",
  "Volleyball",
  "Water Polo",
  "Weightlifting",
  "Windsurfing",
  "Wrestling",
  "Wu Shu",
];
